name: Deploy Doxygen Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'GloveTest/html/**'  # Trigger this workflow when there's a change in the Doxygen output folder

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Create gh-pages branch and push docs
        run: |
          # Create gh-pages branch (if it doesn't exist)
          git checkout --orphan gh-pages
          git rm -rf .

          # Move generated docs to root (or use a specific folder)
          mv GloveTest/html/* .

          # Commit the changes
          git add .
          git commit -m "Deploy Doxygen docs"

          # Push the docs to the gh-pages branch using the PAT
          git remote add origin https://github.com/${{ github.repository }}
          git push --force origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.GENERATE_SITES_SECRET }}
