name: Generate Doxygen Docs

on:
  push:
    branches:
      - main

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Doxygen and generate documentation
      - name: Set up Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen

      - name: Generate Doxygen documentation
        run: |
          cd GloveTest
          doxygen Doxyfile
