name: Doxygen Documentation

# Trigger the workflow on push or pull request to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Doxygen
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      # Step 3: Generate Doxygen documentation
      - name: Run Doxygen
        run: |
          cd GloveTest
          doxygen Doxyfile

      # Step 4: Upload documentation to GitHub Pages
      - name: Deploy Doxygen Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
          publish_dir: ./docs/html  # Doxygen generates docs in 'docs/html'
          user_name: 'GitHub Actions'
          user_email: 'github-actions@github.com'
