name: Doxygen Documentation

# Run on any push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Use Ubuntu for the CI environment

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Doxygen
    - name: Set up Doxygen
      run: sudo apt-get install doxygen

    # Step 3: Run Doxygen with your Doxyfile
    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    # Optional: Upload the generated documentation to a GitHub Pages site or elsewhere
    # Uncomment the following lines if you want to upload the generated docs
    # - name: Upload documentation to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./docs/html
