name: Generate and Deploy Doxygen Docs to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'GloveTest/**'  # Trigger on changes in the GloveTest directory

jobs:
  generate_and_deploy_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevent overwriting credentials

      # Set up Doxygen and generate documentation
      - name: Set up Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate Doxygen documentation
        run: |
          cd GloveTest
          doxygen Doxyfile

      # Move generated docs to root directory
      - name: Move docs to root
        run: |
          mv GloveTest/html/* ./

      # Create and switch to gh-pages branch if it doesn't exist
      - name: Create and switch to gh-pages branch
        run: |
          git fetch origin
          git checkout origin/gh-pages || git checkout --orphan gh-pages
          git rm -rf .
        continue-on-error: true  # Proceed if the branch already exists

      # Set up Git config
      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      # Commit and push changes to the gh-pages branch
      - name: Commit and push docs to gh-pages branch
        run: |
          git add .
          git commit -m "Deploy Doxygen docs"
          git push origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.BOT_SITE_GENERATION }}
